version: '3.8'

services:
  frontend:
    image: axe548/wanderlustdevops:wanderlust_frontend-v1.0.1
    ports:
      - 3000:80
    networks:
      - frontend_network
    environment:
      - VITE_API_PATH=http://localhost:8080

  backend:
    image: axe548/wanderlustdevops:wanderlust_backend-v1.0.1
    ports:
      - 5000:8080
    networks:
      - backend_network
    environment:
      - PORT=8080
      - NODE_ENV=Development # production
      - JWT_SECRET=
      - MONGODB_URI=
      - REDIS_URL=redis://127.0.0.1:6379
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:8080
      - ACCESS_COOKIE_MAXAGE=120000
      - ACCESS_TOKEN_EXPIRES_IN=120s
      - REFRESH_COOKIE_MAXAGE=120000
      - REFRESH_TOKEN_EXPIRES_IN=120s
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=

networks:
  frontend_network:
    driver: bridge

  backend_network:
    driver: bridge