FROM node:23 AS build

COPY frontend/ /frontend/

WORKDIR /frontend/

RUN  echo "VITE_API_PATH=http://a22e495572461413087e7533d01eaa26-68576424.us-east-1.elb.amazonaws.com:5000" > .env && npm install eslint@^9.10.0 --save-dev && npm run build

FROM nginx:alpine

COPY --from=build /frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]