name: "Deploy to EKS"
description: "Deploy to EKS"

inputs:
  aws_id:
    description: "AWS ACCESS KEY ID"
    required: true
  aws_key:
    description: "AWS SECRET ACCESS KEY"
    required: true
  jwt_name:
    description: "jwt_name"
    required: true
  db_uri:
    description: "db_uri"
    required: true
  google_client_id:
    description: "google_client_id"
    required: true
  google_client_secret:
    description: "google_client_secret"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws_id }}
        aws-secret-access-key: ${{ inputs.aws_key }}
        aws-region: us-east-1

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name eksWanderlust --region us-east-1
      shell: bash

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/deployments/
        kubectl apply -f k8s/services/
      shell: bash
