apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wanderlustdevops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: axe548/wanderlustdevops:wanderlust_backend-v1.0.1
        ports:
        - containerPort: 8080
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: jwt-secret.txt
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-secret.txt
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: googleclientid-secret
              key: googleclientid-secret.txt
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: googleclientsecret-secret
              key: googleclientsecret-secret.txt
        envFrom:
        - configMapRef:
            name: wanderlust-config
