apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wanderlustdevops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: axe548/wanderlustdevops:wanderlust_frontend-v1.0.1
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_PATH
          value: "http://localhost:5000"