name: "Infrastructure"
description: "Generate Infrastructure on AWS"

inputs:
  aws_id:
    description: "AWS ACCESS KEY ID"
    required: true
  aws_key:
    description: "AWS SECRET ACCESS KEY"
    required: true

runs:
    using: "composite"
    steps:
      - name: Build IaC
        run: echo "Building infrastructure..."
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v4.1.7
        shell: bash

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
        shell: bash

      - name: Terraform Init
        run: terraform init
        shell: bash

      - name: Terraform Plan
        id: plan
        run: terraform plan
        shell: bash

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve
        shell: bash