name: "Infrastructure"
description: "Generate Infrastructure on AWS"

inputs:
  aws_id:
    description: "AWS ACCESS KEY ID"
    required: true
  aws_key:
    description: "AWS SECRET ACCESS KEY"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build IaC
      run: echo "Building infrastructure..."
      shell: bash

    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Create AWS config
      run: |
        mkdir -p ~/.aws
        cp .aws/config.example ~/.aws/config
        touch  ~/.aws/credentials
       
        echo "[default]" >> ~/.aws/credentials
        echo "aws_access_key_id = ${{ inputs.aws_id }}" >> ~/.aws/credentials
        echo "aws_secret_access_key = ${{ inputs.aws_key }}" >> ~/.aws/credentials
      shell: bash

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.7

    - name: Terraform Init
      working-directory: terraform
      run: terraform init
      shell: bash

    - name: Terraform Plan
      id: plan
      working-directory: terraform
      run: terraform plan
      shell: bash

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      working-directory: terraform
      run: terraform apply -auto-approve
      shell: bash