apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: wanderlustdevops
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 80
  type: LoadBalancer
