name: CI/CD Pipeline

on:
    push:
        branches:
            - master

jobs:
    testing:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4.1.7
            
          - name: Testing
            uses: ./.github/actions/testing
          
    image_build:
      runs-on: ubuntu-latest
      # needs: [testing]
      steps:
        - name: Checkout code
          uses: actions/checkout@v4.1.7
          
        - name: Build and Push Image to Docker Hub
          uses: ./.github/actions/build
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

    iac:
      runs-on: ubuntu-latest
      # needs: [image_build]
      steps:
        - name: Checkout code
          uses: actions/checkout@v4.1.7
          
        - name: Infrastructure
          uses: ./.github/actions/iac
          with:
            aws_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    k8s_deploy:
      runs-on: ubuntu-latest
      # needs: [image_build]
      steps:
        - name: Checkout code
          uses: actions/checkout@v4.1.7
          
        - name: K8s
          uses: ./.github/actions/k8s
          with:
            aws_id: ${{ secrets.AWS_ACCESS_KEY_ID_ADMIN_EKS }}
            aws_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ADMIN_EKS }}
            jwt_name: ${{ secrets.JWT_NAME }}
            db_uri: ${{ secrets.MONGODBSECRET }}
            google_client_id: ${{ secrets.GOOGLECLIENTID }}
            google_client_secret: ${{ secrets.GOOGLECLIENTSECRET }}