name: CI/CD Pipeline

on:
    push:
        branches:
            - master

jobs:
    testing:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4.1.7
            
          - name: Testing
            uses: ./.github/actions/testing
          
    image_build:
      runs-on: ubuntu-latest
      # needs: [testing]
      steps:
        - name: Checkout code
          uses: actions/checkout@v4.1.7
          
        - name: Build and Push Image to Docker Hub
          uses: ./.github/actions/build
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}